# Generated by Django 4.2.4 on 2023-09-17 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productcategory_alter_wine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.reviews'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=455, unique=True, verbose_name='URL'),
        ),
    ]
