# Generated by Django 4.2.4 on 2023-09-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_wine_reviews_alter_wine_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='slug',
            field=models.SlugField(max_length=455, unique=True, verbose_name='URL'),
        ),
    ]
