# Generated by Django 4.2.4 on 2023-09-17 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_wine_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='reviews',
        ),
        migrations.AddField(
            model_name='reviews',
            name='product',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='shop.wine'),
        ),
    ]
