# Generated by Django 4.2.4 on 2023-10-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_wine_reviews_reviews_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.FloatField(),
        ),
    ]
