# Generated by Django 4.2.4 on 2023-10-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_wine_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
