# Generated by Django 4.2.4 on 2023-11-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_wine_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='stars_count',
            field=models.IntegerField(null=True),
        ),
    ]
