# Generated by Django 4.2.4 on 2023-09-17 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('street_address_1', models.TextField()),
                ('street_address_2', models.TextField(null=True)),
                ('city', models.CharField(max_length=155)),
                ('state', models.CharField(max_length=155)),
                ('zip_code', models.CharField(max_length=155)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.checkout')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=355)),
                ('name', models.CharField(max_length=155, null=True)),
                ('last_name', models.CharField(max_length=155, null=True)),
                ('display_name', models.CharField(default=models.CharField(max_length=255), max_length=255)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.checkout')),
            ],
        ),
    ]
