# Generated by Django 4.2.4 on 2023-11-10 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_checkoutaddress_orderinformation_and_more'),
        ('accounts', '0002_remove_shippingaddress_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.checkoutaddress'),
        ),
        migrations.AlterField(
            model_name='user',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.orderinformation'),
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
