# Generated by Django 4.2.4 on 2023-11-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_user_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_orders',
        ),
    ]
