# Generated by Django 4.2.4 on 2023-11-04 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cartitem_cart_items_alter_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.cart'),
        ),
    ]
