# Generated by Django 4.2.4 on 2023-11-04 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_cartitem_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cart'),
        ),
    ]
