# Generated by Django 4.2.4 on 2023-11-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_cartitem_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(default=None, null=True, to='orders.cartitem'),
        ),
    ]
