# Generated by Django 4.2.4 on 2023-11-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_checkout_order_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('street_address_1', models.TextField()),
                ('street_address_2', models.TextField(null=True)),
                ('city', models.CharField(max_length=155)),
                ('state', models.CharField(max_length=155)),
                ('zip_code', models.CharField(max_length=155)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='OrderInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('cancel', 'Cancel'), ('delivered', 'Delivered')], default='pending', max_length=255)),
                ('payment_is', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='cart_information',
        ),
    ]
