# Generated by Django 4.2.4 on 2023-11-10 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_checkoutaddress_orderinformation_and_more'),
        ('accounts', '0003_user_shipping_address_alter_user_orders_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.AddField(
            model_name='orderinformation',
            name='address_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.checkoutaddress'),
        ),
        migrations.AddField(
            model_name='orderinformation',
            name='cart_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.cart'),
        ),
    ]
