# Generated by Django 4.2.4 on 2023-11-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_delete_checkout_orderinformation_address_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinformation',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
