# Generated by Django 4.2.4 on 2023-11-11 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('orders', '0014_alter_orderinformation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutaddress',
            name='session_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
