# Generated by Django 4.2.4 on 2023-11-11 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_checkoutaddress_session_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinformation',
            name='address_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.checkoutaddress'),
        ),
    ]
