# Generated by Django 4.2.4 on 2023-11-11 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_orderinformation_address_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinformation',
            name='cart_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.cart'),
        ),
    ]
