# Generated by Django 4.2.4 on 2023-11-12 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0020_alter_checkoutaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='session_guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderinformation',
            name='address_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.checkoutaddress'),
        ),
        migrations.AlterField(
            model_name='orderinformation',
            name='cart_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cart'),
        ),
    ]
