# Generated by Django 4.2.4 on 2023-11-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_orderinformation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinformation',
            name='payment_method',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
